services:
  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - ./volumes/postgresql_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - exam
  
  crud_example:
    build: 
      context: crud_example
      dockerfile: Dockerfile-crud_example
    ports:
      - "8000:80"
      - "8888:8888"
    volumes:
      - ./crud_example:/app/crud_example
    env_file:
      - .env
    command: ["python","-m","debugpy","--listen","0.0.0.0:8888","--wait-for-client","-m","uvicorn","crud_example.main:app","--host","0.0.0.0","--port","80","--reload"]
    depends_on:
      - db
    networks:
      - exam

networks:
  exam:
    driver: bridge
    #external: true