services:
  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - ./volumes/postgresql_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - exam
  
  crud_example:
    build: 
      context: .
      dockerfile: Dockerfile-crud_example
    ports:
      - "8000:80"
    volumes:
      - ./crud_example:/crud_example
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - exam

networks:
  exam:
    driver: bridge
    #external: true