services:
  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - ./volumes/postgresql_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - exam

  payments_manager:
    build: 
      context: payments_manager
      dockerfile: Dockerfile
    ports:
      - "8010:80"
      - "8888:8888"
    volumes:
      - ./payments_manager:/app/payments_manager
    env_file:
      - .env
    command: ["python","-m","debugpy","--listen","0.0.0.0:8888","--wait-for-client","-m","uvicorn","payments_manager.main:app","--host","0.0.0.0","--port","80","--reload"] # debugpy
    depends_on:
      - db
    networks:
      - exam

  accounts_microservice:
    build: 
      context: accounts_microservice
      dockerfile: Dockerfile
    ports:
      - "8013:8013"
    volumes:
      - ./accounts_microservice:/app/accounts_microservice
    env_file:
      - .env
    command: ["uvicorn", "accounts_microservice.main:app", "--host", "0.0.0.0", "--port", "8013", "--reload"]
    depends_on:
      - db
      - rabbitmq
    networks:
      - exam

  payments_dispatcher:
    build: 
      context: payments_dispatcher
      dockerfile: Dockerfile
    ports:
      - "8011:8011"
    volumes:
      - ./payments_dispatcher:/app/payments_dispatcher
    env_file:
      - .env
    command: ["uvicorn", "payments_dispatcher.main:app", "--host", "0.0.0.0", "--port", "8011", "--reload"]
    depends_on:
      - db
    networks:
      - exam
  
  rabbitmq:
    image: rabbitmq:3.9.29-management-alpine
    container_name: rabbitmq
    #ports:
    #    - '15672:15672'
    volumes:
      - ./volumes/rabbitmq/data:/var/lib/rabbitmq/data
      - ./volumes/rabbitmq/log:/var/log/rabbitmq/
    # logging:
    #   driver: none
    networks:
      - exam

  crud_example:
    build: 
      context: crud_example
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./crud_example:/app/crud_example
    env_file:
      - .env
    command: ["uvicorn", "crud_example.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    depends_on:
      - db
    networks:
      - exam

networks:
  exam:
    driver: bridge
    #external: true